### ISSUE TITLE
JSON version

### ISSUE THREAD

**Issue by scruffian** [morphgnt/tischendorf#2]
Any tips on how to convert this to JSON? I'd like to use it to make something like this: https://www.npmjs.com/package/morphhb

**Comment by emg** [comment]
Would an OSIS XML version make it any easier?  I might be able to convert the Tischendorf text to OSIS XML.

Other than that, you would need to:a

a) Write a program which reads the text into memory.
b) Emit it as JSON from memory.

The file format is defined in the README.

**Comment by scruffian** [comment]
XML would definitely be a step in the right direction yeah :)

**Comment by emg** [comment]
Hello,

I have released an OSIS XML version of the Tischendorf data (version 2.8) over at:

https://github.com/morphgnt/tischendorf-data/ 

Enjoy!

Ulrik Sandborg-Petersen

**Comment by scruffian** [comment]
Thanks!

**Comment by scruffian** [comment]
I think there's a syntax error in the XML. It's formatted like this:

```<verse osisID="Matt.1.2" sID="Matt.1.2"/> ... <verse eID="Matt.1.2"/>```

I think it should be like this:

```<verse osisID="Matt.1.2" sID="Matt.1.2"> ... </verse eID="Matt.1.2">```

**Comment by emg** [comment]
That's not a syntax error. Look in the accompanying XML Schema (osisCore2.1.1.xsd). 

The "verse" element is a milestone, not a container.  The starting milestone element is identified by the presence of the @sID attribute. The ending milestone is identified by the presence of an @eID attribute.
